import ACC.Formula.NormalForm.ModPAnd
import ACC.Formula.Probabilistic.AndModSwap
import ACC.Formula.Probabilistic.Properties

namespace Circuits.ACC.ProbabilisticACCFormula

/-! ## Polynomial compilation of AND/MOD formulas -/

/-- A monomial is a conjunction of input literals; a polynomial is a list of
monomials whose multiplicities are coefficients modulo `p`. -/
abbrev BooleanPolynomial (p : Nat) :=
  List (List (ProbabilisticACCFormula p))

/-- Distributive product of two expanded Boolean polynomials. -/
def polynomialMul {p : Nat} (left right : BooleanPolynomial p) :
    BooleanPolynomial p :=
  left.flatMap fun leftMonomial =>
    right.map fun rightMonomial => leftMonomial ++ rightMonomial

/-- An expanded natural power of a Boolean polynomial. -/
def polynomialPow {p : Nat} (polynomial : BooleanPolynomial p) :
    Nat → BooleanPolynomial p
  | 0 => [[]]
  | exponent + 1 => polynomialMul polynomial (polynomialPow polynomial exponent)

/-- Additive negation of an expanded polynomial over `ZMod p`. -/
def polynomialNeg (p : Nat) (polynomial : BooleanPolynomial p) :
    BooleanPolynomial p :=
  (List.replicate (p - 1) polynomial).flatten

/-- The Fermat zero-indicator polynomial `1 - polynomial^(p - 1)`. -/
def zeroIndicatorPolynomial (p : Nat) (polynomial : BooleanPolynomial p) :
    BooleanPolynomial p :=
  [[]] ++ polynomialNeg p (polynomialPow polynomial (p - 1))

/-- Number of monomials generated by a pairwise polynomial product. -/
theorem polynomialMul_length {p : Nat} (left right : BooleanPolynomial p) :
    (polynomialMul left right).length = left.length * right.length := by
  induction left with
  | nil => simp [polynomialMul]
  | cons monomial monomials ih =>
      simp [polynomialMul, Nat.add_mul, Nat.add_comm]

/-- Number of monomials in an expanded power. -/
theorem polynomialPow_length {p : Nat} (polynomial : BooleanPolynomial p)
    (exponent : Nat) :
    (polynomialPow polynomial exponent).length = polynomial.length ^ exponent := by
  induction exponent with
  | zero => simp [polynomialPow]
  | succ exponent ih =>
      rw [polynomialPow, polynomialMul_length, ih, pow_succ']

/-- Negation repeats every monomial `p - 1` times. -/
theorem polynomialNeg_length {p : Nat} (polynomial : BooleanPolynomial p) :
    (polynomialNeg p polynomial).length = (p - 1) * polynomial.length := by
  simp [polynomialNeg]

/-- Monomial count of the Fermat zero indicator. -/
theorem zeroIndicatorPolynomial_length {p : Nat}
    (polynomial : BooleanPolynomial p) :
    (zeroIndicatorPolynomial p polynomial).length =
      1 + (p - 1) * polynomial.length ^ (p - 1) := by
  simp [zeroIndicatorPolynomial, polynomialNeg_length, polynomialPow_length,
    Nat.add_comm]

mutual

/-- Expand the Boolean value of an AND/MOD formula as a polynomial in its
input literals.  The `notGate` and `orGate` branches make the function total;
the correctness theorem excludes them with `HasOnlyAndModGates`. -/
def compileValuePolynomial {p : Nat} :
    ProbabilisticACCFormula p → BooleanPolynomial p
  | @ProbabilisticACCFormula.input _ idx negated =>
      [[ProbabilisticACCFormula.input idx negated]]
  | .constant true _ => [[]]
  | .constant false _ => []
  | .notGate _ => []
  | .andGate formulas => compileProductPolynomial formulas
  | .orGate _ => []
  | .modGate formulas =>
      zeroIndicatorPolynomial p (compileSumPolynomial formulas)

/-- Sum the value-polynomials of a list of formulas. -/
def compileSumPolynomial {p : Nat} :
    List (ProbabilisticACCFormula p) → BooleanPolynomial p
  | [] => []
  | formula :: formulas =>
      compileValuePolynomial formula ++ compileSumPolynomial formulas

/-- Multiply the value-polynomials of a list of formulas. -/
def compileProductPolynomial {p : Nat} :
    List (ProbabilisticACCFormula p) → BooleanPolynomial p
  | [] => [[]]
  | formula :: formulas =>
      polynomialMul (compileValuePolynomial formula)
        (compileProductPolynomial formulas)

end

mutual

/-- A syntactic exponent controlling algebraic expansion.  AND gates add
child ranks, while modulo gates multiply the largest child rank by only a
modulus-dependent factor. -/
def compilationRank {p : Nat} : ProbabilisticACCFormula p → Nat
  | .input _ _ => 1
  | .constant _ _ => 1
  | .notGate _ => 0
  | .andGate formulas => compilationProductRank formulas
  | .orGate _ => 0
  | .modGate formulas => p * (compilationMaxRank formulas + 2)

/-- Largest compilation rank in a list. -/
def compilationMaxRank {p : Nat} :
    List (ProbabilisticACCFormula p) → Nat
  | [] => 0
  | formula :: formulas =>
      max (compilationRank formula) (compilationMaxRank formulas)

/-- Sum of compilation ranks in a product. -/
def compilationProductRank {p : Nat} :
    List (ProbabilisticACCFormula p) → Nat
  | [] => 0
  | formula :: formulas =>
      compilationRank formula + compilationProductRank formulas

end


/-- The elementary numerical estimate used at modulo gates: if a child sum
has at most `base^(rank+1)` monomials, its Fermat zero indicator has at most
`base^(p*(rank+2))` monomials. -/
private theorem zeroIndicator_count_le (p base count rank : Nat)
    (hp : 2 ≤ p) (h_base : 2 ≤ base) (hp_base : p ≤ base)
    (h_count : count ≤ base ^ (rank + 1)) :
    1 + (p - 1) * count ^ (p - 1) ≤ base ^ (p * (rank + 2)) := by
  have h_power : count ^ (p - 1) ≤
      base ^ ((rank + 1) * (p - 1)) := by
    calc
      count ^ (p - 1) ≤ (base ^ (rank + 1)) ^ (p - 1) := by gcongr
      _ = base ^ ((rank + 1) * (p - 1)) := by rw [Nat.pow_mul]
  let exponent := (rank + 1) * (p - 1)
  have h_one : 1 ≤ base ^ exponent := Nat.one_le_pow _ _ (by omega)
  have h_coefficient : p - 1 ≤ base := by omega
  have h_exponent : exponent + 2 ≤ p * (rank + 2) := by
    dsimp [exponent]
    calc
      (rank + 1) * (p - 1) + 2 ≤ (rank + 1) * p + p :=
        Nat.add_le_add
          (Nat.mul_le_mul_left (rank + 1) (Nat.sub_le p 1)) hp
      _ = p * (rank + 2) := by ring
  calc
    1 + (p - 1) * count ^ (p - 1) ≤
        base ^ exponent + base * base ^ exponent := by gcongr
    _ ≤ base * base ^ exponent + base * base ^ exponent := by
      gcongr
      calc
        base ^ exponent = 1 * base ^ exponent := by omega
        _ ≤ base * base ^ exponent :=
          Nat.mul_le_mul_right (base ^ exponent) (by omega)
    _ = 2 * base ^ (exponent + 1) := by
      rw [pow_succ]
      ring
    _ ≤ base * base ^ (exponent + 1) := by gcongr
    _ = base ^ (exponent + 2) := by rw [pow_succ]; ring
    _ ≤ base ^ (p * (rank + 2)) :=
      Nat.pow_le_pow_right (by omega) h_exponent

mutual

/-- Maximum monomial degree produced for a formula value. -/
def compilationDegree {p : Nat} : ProbabilisticACCFormula p → Nat
  | .input _ _ => 1
  | .constant _ _ => 0
  | .notGate _ => 0
  | .andGate formulas => compilationProductDegree formulas
  | .orGate _ => 0
  | .modGate formulas => (p - 1) * compilationMaxDegree formulas

/-- Maximum degree among compiled child values in a sum. -/
def compilationMaxDegree {p : Nat} :
    List (ProbabilisticACCFormula p) → Nat
  | [] => 0
  | formula :: formulas =>
      max (compilationDegree formula) (compilationMaxDegree formulas)

/-- Degree of a product of compiled child values. -/
def compilationProductDegree {p : Nat} :
    List (ProbabilisticACCFormula p) → Nat
  | [] => 0
  | formula :: formulas =>
      compilationDegree formula + compilationProductDegree formulas

end


/-- Every monomial in `polynomial` has length at most `degree`. -/
def HasDegreeAtMost {p : Nat} (polynomial : BooleanPolynomial p)
    (degree : Nat) : Prop :=
  ∀ monomial ∈ polynomial, monomial.length ≤ degree

theorem hasDegreeAtMost_mono {p : Nat} {polynomial : BooleanPolynomial p}
    {left right : Nat} (h : HasDegreeAtMost polynomial left)
    (h_le : left ≤ right) : HasDegreeAtMost polynomial right := by
  intro monomial h_monomial
  exact (h monomial h_monomial).trans h_le

theorem polynomialMul_hasDegreeAtMost {p : Nat}
    (left right : BooleanPolynomial p) (leftDegree rightDegree : Nat)
    (h_left : HasDegreeAtMost left leftDegree)
    (h_right : HasDegreeAtMost right rightDegree) :
    HasDegreeAtMost (polynomialMul left right) (leftDegree + rightDegree) := by
  intro monomial h_monomial
  simp only [polynomialMul, List.mem_flatMap, List.mem_map] at h_monomial
  obtain ⟨leftMonomial, h_leftMonomial, rightMonomial,
    h_rightMonomial, rfl⟩ := h_monomial
  simp only [List.length_append]
  exact Nat.add_le_add (h_left leftMonomial h_leftMonomial)
    (h_right rightMonomial h_rightMonomial)

theorem polynomialPow_hasDegreeAtMost {p : Nat}
    (polynomial : BooleanPolynomial p) (degree exponent : Nat)
    (h_polynomial : HasDegreeAtMost polynomial degree) :
    HasDegreeAtMost (polynomialPow polynomial exponent) (exponent * degree) := by
  induction exponent with
  | zero => simp [polynomialPow, HasDegreeAtMost]
  | succ exponent ih =>
      have h_mul := polynomialMul_hasDegreeAtMost polynomial
        (polynomialPow polynomial exponent) degree (exponent * degree)
        h_polynomial ih
      apply hasDegreeAtMost_mono h_mul
      simp [Nat.succ_mul, Nat.add_comm]

theorem polynomialNeg_hasDegreeAtMost {p : Nat}
    (polynomial : BooleanPolynomial p) (degree : Nat)
    (h_polynomial : HasDegreeAtMost polynomial degree) :
    HasDegreeAtMost (polynomialNeg p polynomial) degree := by
  intro monomial h_monomial
  simp only [polynomialNeg, List.mem_flatten] at h_monomial
  obtain ⟨copy, h_copy, h_monomial⟩ := h_monomial
  have h_copy_eq : copy = polynomial := List.eq_of_mem_replicate h_copy
  subst copy
  exact h_polynomial monomial h_monomial

theorem zeroIndicatorPolynomial_hasDegreeAtMost {p : Nat}
    (polynomial : BooleanPolynomial p) (degree : Nat)
    (h_polynomial : HasDegreeAtMost polynomial degree) :
    HasDegreeAtMost (zeroIndicatorPolynomial p polynomial) ((p - 1) * degree) := by
  intro monomial h_monomial
  simp only [zeroIndicatorPolynomial, List.mem_append, List.mem_cons,
    List.not_mem_nil, or_false] at h_monomial
  rcases h_monomial with rfl | h_monomial
  · simp
  · exact polynomialNeg_hasDegreeAtMost
      (polynomialPow polynomial (p - 1)) ((p - 1) * degree)
      (polynomialPow_hasDegreeAtMost polynomial degree (p - 1) h_polynomial)
      monomial h_monomial

mutual

/-- Degree bound for the compiled value polynomial. -/
theorem compileValuePolynomial_hasDegreeAtMost {p : Nat}
    (formula : ProbabilisticACCFormula p) :
    HasDegreeAtMost (compileValuePolynomial formula)
      (compilationDegree formula) := by
  match formula with
  | .input .. => simp [compileValuePolynomial, compilationDegree,
      HasDegreeAtMost]
  | .constant value label =>
      cases value <;> simp [compileValuePolynomial, compilationDegree,
        HasDegreeAtMost]
  | .notGate formula => simp [compileValuePolynomial, compilationDegree,
      HasDegreeAtMost]
  | .orGate formulas => simp [compileValuePolynomial, compilationDegree,
      HasDegreeAtMost]
  | .andGate formulas => exact compileProductPolynomial_hasDegreeAtMost formulas
  | .modGate formulas =>
      exact zeroIndicatorPolynomial_hasDegreeAtMost
        (compileSumPolynomial formulas) (compilationMaxDegree formulas)
        (compileSumPolynomial_hasDegreeAtMost formulas)

/-- Degree bound for a compiled sum. -/
theorem compileSumPolynomial_hasDegreeAtMost {p : Nat}
    (formulas : List (ProbabilisticACCFormula p)) :
    HasDegreeAtMost (compileSumPolynomial formulas)
      (compilationMaxDegree formulas) := by
  match formulas with
  | [] => simp [compileSumPolynomial, compilationMaxDegree, HasDegreeAtMost]
  | formula :: formulas =>
      intro monomial h_monomial
      simp only [compileSumPolynomial, compilationMaxDegree, List.mem_append]
        at h_monomial ⊢
      rcases h_monomial with h_monomial | h_monomial
      · exact (compileValuePolynomial_hasDegreeAtMost formula monomial
          h_monomial).trans (Nat.le_max_left _ _)
      · exact (compileSumPolynomial_hasDegreeAtMost formulas monomial
          h_monomial).trans (Nat.le_max_right _ _)

/-- Degree bound for a compiled product. -/
theorem compileProductPolynomial_hasDegreeAtMost {p : Nat}
    (formulas : List (ProbabilisticACCFormula p)) :
    HasDegreeAtMost (compileProductPolynomial formulas)
      (compilationProductDegree formulas) := by
  match formulas with
  | [] => simp [compileProductPolynomial, compilationProductDegree,
      HasDegreeAtMost]
  | formula :: formulas =>
      exact polynomialMul_hasDegreeAtMost (compileValuePolynomial formula)
        (compileProductPolynomial formulas) (compilationDegree formula)
        (compilationProductDegree formulas)
        (compileValuePolynomial_hasDegreeAtMost formula)
        (compileProductPolynomial_hasDegreeAtMost formulas)

end

mutual

/-- Exact monomial count of `compileValuePolynomial`. -/
def compilationMonomialCount {p : Nat} : ProbabilisticACCFormula p → Nat
  | .input _ _ => 1
  | .constant true _ => 1
  | .constant false _ => 0
  | .notGate _ => 0
  | .andGate formulas => compilationProductCount formulas
  | .orGate _ => 0
  | .modGate formulas =>
      1 + (p - 1) * compilationSumCount formulas ^ (p - 1)

/-- Monomial count of a compiled sum. -/
def compilationSumCount {p : Nat} : List (ProbabilisticACCFormula p) → Nat
  | [] => 0
  | formula :: formulas =>
      compilationMonomialCount formula + compilationSumCount formulas

/-- Monomial count of a compiled product. -/
def compilationProductCount {p : Nat} :
    List (ProbabilisticACCFormula p) → Nat
  | [] => 1
  | formula :: formulas =>
      compilationMonomialCount formula * compilationProductCount formulas

end

private theorem nodeCount_le_sum_of_mem {p : Nat}
    {formula : ProbabilisticACCFormula p}
    {formulas : List (ProbabilisticACCFormula p)} (h_formula : formula ∈ formulas) :
    formula.nodeCount ≤ (formulas.map nodeCount).sum := by
  induction formulas with
  | nil => simp at h_formula
  | cons head tail ih =>
      simp only [List.mem_cons] at h_formula
      simp only [List.map_cons, List.sum_cons]
      rcases h_formula with rfl | h_formula
      · omega
      · exact (ih h_formula).trans (Nat.le_add_left _ _)

private theorem length_le_sum_nodeCount {p : Nat}
    (formulas : List (ProbabilisticACCFormula p)) :
    formulas.length ≤ (formulas.map nodeCount).sum := by
  induction formulas with
  | nil => simp
  | cons formula formulas ih =>
      simp only [List.length_cons, List.map_cons, List.sum_cons]
      have h_pos := nodeCount_pos formula
      omega

mutual

/-- The expanded monomial count is at most a fixed polynomial base raised to
`compilationRank`.  The parameter `nodeBound` lets recursive calls use the
same base, which is essential at unbounded-fan-in modulo gates. -/
theorem compilationMonomialCount_le_pow {p : Nat} (hp : 2 ≤ p)
    (formula : ProbabilisticACCFormula p) (nodeBound : Nat)
    (h_nodes : formula.nodeCount ≤ nodeBound) :
    compilationMonomialCount formula ≤
      (2 * p * nodeBound) ^ compilationRank formula := by
  have h_nodeBound : 0 < nodeBound :=
    lt_of_lt_of_le (nodeCount_pos formula) h_nodes
  match formula with
  | .input inputRef negated =>
      have h_base : 0 < 2 * p * nodeBound := by positivity
      change 1 ≤ (2 * p * nodeBound) ^ 1
      simp only [pow_one]
      omega
  | .constant value label =>
      cases value with
      | false => simp [compilationMonomialCount, compilationRank]
      | true =>
          have h_base : 0 < 2 * p * nodeBound := by positivity
          change 1 ≤ (2 * p * nodeBound) ^ 1
          simp only [pow_one]
          omega
  | .notGate child => simp [compilationMonomialCount, compilationRank]
  | .orGate children => simp [compilationMonomialCount, compilationRank]
  | .andGate children =>
      apply compilationProductCount_le_pow hp children nodeBound
      intro child h_child
      exact (nodeCount_le_sum_of_mem h_child).trans
        (by simp [nodeCount] at h_nodes; omega)
  | .modGate children =>
      let base := 2 * p * nodeBound
      have h_base : 2 ≤ base := by
        dsimp [base]
        nlinarith
      have hp_base : p ≤ base := by
        dsimp [base]
        nlinarith
      have h_children : ∀ child ∈ children, child.nodeCount ≤ nodeBound := by
        intro child h_child
        exact (nodeCount_le_sum_of_mem h_child).trans
          (by simp [nodeCount] at h_nodes; omega)
      have h_sum := compilationSumCount_le_pow hp children nodeBound h_children
      have h_length : children.length ≤ nodeBound := by
        calc
          children.length ≤ (children.map nodeCount).sum :=
            length_le_sum_nodeCount children
          _ ≤ nodeBound := by simp [nodeCount] at h_nodes; omega
      have h_sum_power : compilationSumCount children ≤
          base ^ (compilationMaxRank children + 1) := by
        calc
          compilationSumCount children ≤
              children.length * base ^ compilationMaxRank children := by
            simpa [base] using h_sum
          _ ≤ nodeBound * base ^ compilationMaxRank children := by gcongr
          _ ≤ base * base ^ compilationMaxRank children := by
            gcongr
            dsimp [base]
            nlinarith
          _ = base ^ (compilationMaxRank children + 1) := by
            rw [pow_succ]
            ring
      simpa [compilationMonomialCount, compilationRank, base] using
        zeroIndicator_count_le p base (compilationSumCount children)
          (compilationMaxRank children) hp h_base hp_base h_sum_power

/-- A compiled sum has at most one maximal-rank contribution per list
element. -/
theorem compilationSumCount_le_pow {p : Nat} (hp : 2 ≤ p)
    (formulas : List (ProbabilisticACCFormula p)) (nodeBound : Nat)
    (h_nodes : ∀ formula ∈ formulas, formula.nodeCount ≤ nodeBound) :
    compilationSumCount formulas ≤
      formulas.length * (2 * p * nodeBound) ^ compilationMaxRank formulas := by
  match formulas with
  | [] => simp [compilationSumCount, compilationMaxRank]
  | formula :: formulas =>
      have h_nodeBound : 0 < nodeBound :=
        lt_of_lt_of_le (nodeCount_pos formula) (h_nodes formula (by simp))
      have h_base : 0 < 2 * p * nodeBound := by positivity
      have h_head := compilationMonomialCount_le_pow hp formula nodeBound
        (h_nodes formula (by simp))
      have h_tail := compilationSumCount_le_pow hp formulas nodeBound (by
        intro child h_child
        exact h_nodes child (by simp [h_child]))
      have h_head_pow :
          (2 * p * nodeBound) ^ compilationRank formula ≤
            (2 * p * nodeBound) ^
              max (compilationRank formula) (compilationMaxRank formulas) := by
        exact Nat.pow_le_pow_right h_base
          (Nat.le_max_left _ _)
      have h_tail_pow :
          (2 * p * nodeBound) ^ compilationMaxRank formulas ≤
            (2 * p * nodeBound) ^
              max (compilationRank formula) (compilationMaxRank formulas) := by
        exact Nat.pow_le_pow_right h_base
          (Nat.le_max_right _ _)
      simp only [compilationSumCount, compilationMaxRank, List.length_cons]
      calc
        compilationMonomialCount formula + compilationSumCount formulas ≤
            (2 * p * nodeBound) ^ compilationRank formula +
              formulas.length *
                (2 * p * nodeBound) ^ compilationMaxRank formulas :=
          Nat.add_le_add h_head h_tail
        _ ≤ (2 * p * nodeBound) ^
              max (compilationRank formula) (compilationMaxRank formulas) +
            formulas.length *
              (2 * p * nodeBound) ^
                max (compilationRank formula) (compilationMaxRank formulas) := by
          gcongr
        _ = (formulas.length + 1) *
            (2 * p * nodeBound) ^
              max (compilationRank formula) (compilationMaxRank formulas) := by
          ring

/-- Products add ranks, so their monomial counts multiply within the same
base. -/
theorem compilationProductCount_le_pow {p : Nat} (hp : 2 ≤ p)
    (formulas : List (ProbabilisticACCFormula p)) (nodeBound : Nat)
    (h_nodes : ∀ formula ∈ formulas, formula.nodeCount ≤ nodeBound) :
    compilationProductCount formulas ≤
      (2 * p * nodeBound) ^ compilationProductRank formulas := by
  match formulas with
  | [] => simp [compilationProductCount, compilationProductRank]
  | formula :: formulas =>
      have h_head := compilationMonomialCount_le_pow hp formula nodeBound
        (h_nodes formula (by simp))
      have h_tail := compilationProductCount_le_pow hp formulas nodeBound (by
        intro child h_child
        exact h_nodes child (by simp [h_child]))
      simp only [compilationProductCount, compilationProductRank, pow_add]
      exact Nat.mul_le_mul h_head h_tail

end

/-- Self-contained monomial-count bound using the formula's own node count. -/
theorem compilationMonomialCount_le {p : Nat} (hp : 2 ≤ p)
    (formula : ProbabilisticACCFormula p) :
    compilationMonomialCount formula ≤
      (2 * p * formula.nodeCount) ^ compilationRank formula :=
  compilationMonomialCount_le_pow hp formula formula.nodeCount le_rfl

private theorem max_map_le_of_forall {α : Type} (values : List α)
    (measure : α → Nat) (bound : Nat)
    (h_values : ∀ value ∈ values, measure value ≤ bound) :
    (values.map measure).max?.getD 0 ≤ bound := by
  induction values with
  | nil => simp
  | cons value values ih =>
      have h_tail : ∀ child ∈ values, measure child ≤ bound := by
        intro child h_child
        exact h_values child (by simp [h_child])
      simp only [List.map_cons]
      rw [show (measure value :: values.map measure).max?.getD 0 =
        max (measure value) ((values.map measure).max?.getD 0) by
          cases values <;> simp [List.max?_cons]]
      exact max_le (h_values value (by simp)) (ih h_tail)

private theorem sum_map_le_length_mul {α : Type} (values : List α)
    (measure : α → Nat) (bound : Nat)
    (h_values : ∀ value ∈ values, measure value ≤ bound) :
    (values.map measure).sum ≤ values.length * bound := by
  induction values with
  | nil => simp
  | cons value values ih =>
      have h_tail : ∀ child ∈ values, measure child ≤ bound := by
        intro child h_child
        exact h_values child (by simp [h_child])
      simp only [List.map_cons, List.sum_cons, List.length_cons]
      calc
        measure value + (values.map measure).sum ≤
            bound + values.length * bound :=
          Nat.add_le_add (h_values value (by simp)) (ih h_tail)
        _ = (values.length + 1) * bound := by ring

private theorem measure_le_max_map {α : Type} (values : List α)
    (measure : α → Nat) (value : α) (h_value : value ∈ values) :
    measure value ≤ (values.map measure).max?.getD 0 := by
  induction values with
  | nil => simp at h_value
  | cons head tail ih =>
      simp only [List.mem_cons] at h_value
      simp only [List.map_cons]
      rw [show (measure head :: tail.map measure).max?.getD 0 =
        max (measure head) ((tail.map measure).max?.getD 0) by
          cases tail <;> simp [List.max?_cons]]
      rcases h_value with rfl | h_value
      · exact Nat.le_max_left _ _
      · exact (ih h_value).trans (Nat.le_max_right _ _)

theorem compilationMaxRank_eq {p : Nat}
    (formulas : List (ProbabilisticACCFormula p)) :
    compilationMaxRank formulas =
      (formulas.map compilationRank).max?.getD 0 := by
  induction formulas with
  | nil => simp [compilationMaxRank]
  | cons formula formulas ih =>
      simp only [compilationMaxRank, List.map_cons, ih]
      cases formulas <;> simp [List.max?_cons]

theorem compilationProductRank_eq {p : Nat}
    (formulas : List (ProbabilisticACCFormula p)) :
    compilationProductRank formulas =
      (formulas.map compilationRank).sum := by
  induction formulas with
  | nil => simp [compilationProductRank]
  | cons formula formulas ih =>
      simp [compilationProductRank, ih]

mutual

/-- Polynomial degree is bounded by the expansion rank. -/
theorem compilationDegree_le_rank {p : Nat} (formula : ProbabilisticACCFormula p) :
    compilationDegree formula ≤ compilationRank formula := by
  match formula with
  | .input .. => simp [compilationDegree, compilationRank]
  | .constant .. => simp [compilationDegree, compilationRank]
  | .notGate .. => simp [compilationDegree, compilationRank]
  | .orGate .. => simp [compilationDegree, compilationRank]
  | .andGate formulas => exact compilationProductDegree_le_rank formulas
  | .modGate formulas =>
      simp only [compilationDegree, compilationRank]
      exact Nat.mul_le_mul
        (Nat.sub_le p 1)
        (Nat.le_add_right_of_le (compilationMaxDegree_le_rank formulas))

/-- List-maximum form of `compilationDegree_le_rank`. -/
theorem compilationMaxDegree_le_rank {p : Nat}
    (formulas : List (ProbabilisticACCFormula p)) :
    compilationMaxDegree formulas ≤ compilationMaxRank formulas := by
  match formulas with
  | [] => simp [compilationMaxDegree, compilationMaxRank]
  | formula :: formulas =>
      simp only [compilationMaxDegree, compilationMaxRank]
      exact max_le_max (compilationDegree_le_rank formula)
        (compilationMaxDegree_le_rank formulas)

/-- Product-degree form of `compilationDegree_le_rank`. -/
theorem compilationProductDegree_le_rank {p : Nat}
    (formulas : List (ProbabilisticACCFormula p)) :
    compilationProductDegree formulas ≤ compilationProductRank formulas := by
  match formulas with
  | [] => simp [compilationProductDegree, compilationProductRank]
  | formula :: formulas =>
      simp only [compilationProductDegree, compilationProductRank]
      exact Nat.add_le_add (compilationDegree_le_rank formula)
        (compilationProductDegree_le_rank formulas)

end

mutual

/-- Bounded AND fan-in makes compilation rank exponential only in formula
depth, with base `max order (3*p)`. -/
theorem compilationRank_le {p : Nat} (hp : 2 ≤ p)
    (formula : ProbabilisticACCFormula p) (order : Nat)
    (h_formula : HasOnlyAndModGates formula) (h_order : IsOfOrder formula order) :
    compilationRank formula ≤
      (max order (3 * p)) ^ (formula.depth + 1) := by
  let base := max order (3 * p)
  have h_base : 1 ≤ base := by
    dsimp [base]
    omega
  match formula with
  | .input inputRef negated =>
      simpa only [compilationRank, depth, zero_add, pow_one] using h_base
  | .constant value label =>
      simpa only [compilationRank, depth, zero_add, pow_one] using h_base
  | .notGate child => simp [HasOnlyAndModGates] at h_formula
  | .orGate children => simp [HasOnlyAndModGates] at h_formula
  | .andGate children =>
      simp only [HasOnlyAndModGates] at h_formula
      simp only [IsOfOrder] at h_order
      have h_product := compilationProductRank_le hp children order
        h_formula h_order.2
      let maximumDepth := (children.map depth).max?.getD 0
      let power := base ^ (maximumDepth + 1)
      have h_length : children.length ≤ base :=
        h_order.1.trans (Nat.le_max_left _ _)
      simp only [compilationRank, depth]
      have h_bound : compilationProductRank children ≤
          children.length * power := by simpa [base, maximumDepth, power] using h_product
      calc
        compilationProductRank children ≤ children.length * power := h_bound
        _ ≤ base * power := by gcongr
        _ = base ^ (1 + maximumDepth + 1) := by
          rw [show 1 + maximumDepth + 1 = (maximumDepth + 1) + 1 by omega,
            pow_succ]
          ring
        _ = (max order (3 * p)) ^
            (1 + (children.map depth).max?.getD 0 + 1) := rfl
  | .modGate children =>
      simp only [HasOnlyAndModGates] at h_formula
      simp only [IsOfOrder] at h_order
      have h_max := compilationMaxRank_le hp children order h_formula h_order
      let maximumDepth := (children.map depth).max?.getD 0
      let power := base ^ (maximumDepth + 1)
      have h_power : 1 ≤ power := Nat.one_le_pow _ _ (by omega)
      have h_three_p : 3 * p ≤ base := Nat.le_max_right _ _
      simp only [compilationRank, depth]
      have h_bound : compilationMaxRank children ≤ power := by
        simpa [base, maximumDepth, power] using h_max
      calc
        p * (compilationMaxRank children + 2) ≤ p * (power + 2) := by gcongr
        _ ≤ 3 * p * power := by nlinarith
        _ ≤ base * power := by gcongr
        _ = base ^ (1 + maximumDepth + 1) := by
          rw [show 1 + maximumDepth + 1 = (maximumDepth + 1) + 1 by omega,
            pow_succ]
          ring
        _ = (max order (3 * p)) ^
            (1 + (children.map depth).max?.getD 0 + 1) := rfl

/-- Maximum-rank list form of `compilationRank_le`. -/
theorem compilationMaxRank_le {p : Nat} (hp : 2 ≤ p)
    (formulas : List (ProbabilisticACCFormula p)) (order : Nat)
    (h_formulas : ∀ formula ∈ formulas, HasOnlyAndModGates formula)
    (h_order : ∀ formula ∈ formulas, IsOfOrder formula order) :
    compilationMaxRank formulas ≤
      (max order (3 * p)) ^
        ((formulas.map depth).max?.getD 0 + 1) := by
  rw [compilationMaxRank_eq]
  apply max_map_le_of_forall
  intro formula h_formula
  have h_rank := compilationRank_le hp formula order
    (h_formulas formula h_formula) (h_order formula h_formula)
  exact h_rank.trans (Nat.pow_le_pow_right (by omega)
    (Nat.add_le_add_right
      (by
        exact measure_le_max_map formulas depth formula h_formula) 1))

/-- Product-rank list form of `compilationRank_le`. -/
theorem compilationProductRank_le {p : Nat} (hp : 2 ≤ p)
    (formulas : List (ProbabilisticACCFormula p)) (order : Nat)
    (h_formulas : ∀ formula ∈ formulas, HasOnlyAndModGates formula)
    (h_order : ∀ formula ∈ formulas, IsOfOrder formula order) :
    compilationProductRank formulas ≤
      formulas.length * (max order (3 * p)) ^
        ((formulas.map depth).max?.getD 0 + 1) := by
  rw [compilationProductRank_eq]
  apply sum_map_le_length_mul
  intro formula h_formula
  have h_rank := compilationRank_le hp formula order
    (h_formulas formula h_formula) (h_order formula h_formula)
  exact h_rank.trans (Nat.pow_le_pow_right (by omega)
    (Nat.add_le_add_right
      (by
        exact measure_le_max_map formulas depth formula h_formula) 1))

end


mutual

/-- The numeric monomial-count recurrence is exact. -/
theorem compileValuePolynomial_length {p : Nat}
    (formula : ProbabilisticACCFormula p) :
    (compileValuePolynomial formula).length = compilationMonomialCount formula := by
  match formula with
  | .input .. => simp [compileValuePolynomial, compilationMonomialCount]
  | .constant value label =>
      cases value <;> simp [compileValuePolynomial, compilationMonomialCount]
  | .notGate formula => simp [compileValuePolynomial, compilationMonomialCount]
  | .orGate formulas => simp [compileValuePolynomial, compilationMonomialCount]
  | .andGate formulas =>
      exact compileProductPolynomial_length formulas
  | .modGate formulas =>
      rw [compileValuePolynomial, zeroIndicatorPolynomial_length,
        compileSumPolynomial_length]
      rfl

/-- Exact count for a compiled sum. -/
theorem compileSumPolynomial_length {p : Nat}
    (formulas : List (ProbabilisticACCFormula p)) :
    (compileSumPolynomial formulas).length = compilationSumCount formulas := by
  match formulas with
  | [] => simp [compileSumPolynomial, compilationSumCount]
  | formula :: formulas =>
      simp only [compileSumPolynomial, List.length_append,
        compilationSumCount]
      rw [compileValuePolynomial_length, compileSumPolynomial_length]

/-- Exact count for a compiled product. -/
theorem compileProductPolynomial_length {p : Nat}
    (formulas : List (ProbabilisticACCFormula p)) :
    (compileProductPolynomial formulas).length =
      compilationProductCount formulas := by
  match formulas with
  | [] => simp [compileProductPolynomial, compilationProductCount]
  | formula :: formulas =>
      simp only [compileProductPolynomial, polynomialMul_length,
        compilationProductCount]
      rw [compileValuePolynomial_length, compileProductPolynomial_length]

end

end Circuits.ACC.ProbabilisticACCFormula
